### ISSUE TITLE
Set `isUserWallet` or/and `isValid` flag to false when wallet is removed

### ISSUE THREAD

**Issue by kackogut** [solana-mobile/seed-vault-sdk#127]
As per the [specification](https://github.com/solana-mobile/seed-vault-sdk/blob/main/docs/integration_guide.md#putting-it-all-together) I understand that rules for setting `isUserWallet` and `isValid` flags are pretty flexible:

> The wallet can use this as a hint in deciding whether to display the account to the user. In turn, after account discovery, the wallet should set the Accounts_IsUserWallet and/or the Accounts_IsValid flags on all discovered accounts, to ensure that the Seed Vault metadata for the account is up to date.

But should we at any point set those flags to `false`, for example if user removes wallet from our app or deauthorize it?

**Comment by sdlaver** [comment]
I'd recommend that you only set these flags to false if you have a strong signal that the user no longer wants to use the wallet. For e.g., if they remove all funds from it and remove it from your app, that would be a good indicator to set `isValid` to false. However, just removing it from your wallet wouldn't itself be sufficient, since they may just want to use it for a different purpose in another app.

**Comment by kackogut** [comment]
Sounds right, thank you!
